### ISSUE TITLE
Deploy issues & check list

### ISSUE THREAD

**Issue by elon0823** [paust-team/paust-db#72]
배포하기전 체크해야할 사항들 리스트업 해봤습니다. 이슈에 올라와있는 내용이기도 하고 패키징전에 한번 체크하기 위해 정리합니다. 
* * *

### Primary Issues ~02/13

- [x] Third-party Client API 설계 및 테스트 #78 ~ 2/13

  - [x] Godoc 문서화

  - [x] paust-db CLI 디렉토리 구조 변경 #90 

- [x] Docker Packaging 및  Deploy test #63 #69 ~ 2/7

- [x] Error handling interface 처리 #58 

- [x] Logging 처리 #40 

- [x] ReadME 작성 

- [x] versioning 및 배포

### Sub Issues ~ 

- [x] Test Code 삭제(MasterApplication:264~)  #73 #74

### Code Issues ~01/25
@kwjooo @dragon0170

- [x] ~Qualifier byte array & RowKey 구성 변경(길이 관련한 상수 변경도 잊지말고 체크) #41~  -> #77

- [x] ~KeyObject 관련 처리(marshal, unmarshal, print formatting)~ #41  -> #77

- [x] ~Client Read 시 파일로도 읽어올 수 있도록 추가 (kevin 이랑 상의한것)~ -> #77

- [x] ~Client WriteData case 중복코드정리  (kevin 이랑 상의한것)~ -> #77

- [x] Qualifier query 관련 처리 #75 

- [x] Types 관련 처리 #76  

- [x] FixedSalt 함수 제거 #81

- [x] Const 관련 처리

- [x] Client parameter type 변경 #84 

* * *

정도 해서 13일까지 하면 어떨까 합니다. 

현재시점에서 1q 에 추가적으로 반영되고 보완되서 배포해야하는 부분 있으면 논의하면 좋을 것 같네요.

커멘트 추가해주세요.
