### ISSUE TITLE
QA checklist for deploy

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#95]
배포하기전 Feature QA입니다.

Packaging
-
* [x] docker local cluster
* [x] single node from source code guide
* [x] 각기 다른 docker-machine위의 node clustering
* [x] Add Non-validator node

Client
-
* [x] Ed25519 key generate via paust-db client
* [x] Write via paust-db client
  * [x] client file write
  * [x] client directory write
  * [x] client specific ownerkey write
  * [x] client specific qualifier write
  * [x] client stdin write

* [x] query via paust-db client
  * [x] MetaDataQuery
    * [x] specific qualifier MetaDataQuery
    * [x] specific ownerKey MetaDataQuery
    * [x] specific qualifier and ownerKey MetaDataQuery
    * [x] time only MetaDataQuery
  * [x] RealDataQuery
    * [x] paust-db client realdata 입력 시 help 창
    * [x] file query
    * [x] stdin query
